/*
Statground Data_Book_NAVER schema for ClickHouse 26.1.2.11
Execution target: ClickHouse entrypoint / DBeaver migration_admin
Cluster: statground_cluster

Principles:
- ClickHouse is OLAP only and not SSOT.
- Kafka topic book.events is the ingestion boundary from GitHub Actions.
- kafka_handle_error_mode='stream' is used; malformed Kafka rows are stored in Data_Book_NAVER_Log.book_kafka_parse_error.
- Raw/log tables use Replicated*MergeTree local tables + Distributed read/write entry tables.
- Time columns are DateTime64(3, 'Asia/Seoul').
- UUID columns store UUID v7 generated outside ClickHouse.
- Legacy multi-source and marketplace/Shotalk backup tables are migrated into Data_Book_NAVER_Raw/Data_Book_NAVER_Log as support tables for this NAVER book repository; future shared objects can be split into Data_Book_Common_* when needed.
*/

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Log`
ON CLUSTER statground_cluster
COMMENT 'Data_Book_NAVER_Log; NAVER book provider Kafka/event/crawler logs; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Raw`
ON CLUSTER statground_cluster
COMMENT 'Data_Book_NAVER_Raw; NAVER book provider raw/support storage; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Mart`
ON CLUSTER statground_cluster
COMMENT 'Data_Book_NAVER_Mart; NAVER book provider aggregate/statistics tables generated inside ClickHouse; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Log`
COMMENT 'Data_Book_NAVER_Log entrypoint database; NAVER Distributed/Kafka/MV objects; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Raw`
COMMENT 'Data_Book_NAVER_Raw entrypoint database; NAVER Distributed objects; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE DATABASE IF NOT EXISTS `Data_Book_NAVER_Mart`
COMMENT 'Data_Book_NAVER_Mart entrypoint database; NAVER Distributed/statistics objects; OLAP 전용; SSOT 아님; Asia/Seoul 기준';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.book_events_local
ON CLUSTER statground_cluster
(
    event_uuid UUID COMMENT 'Kafka event UUID v7 generated by producer; ClickHouse UUID type; event/log row identifier',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic name; expected book.events; lineage/debug field',
    kafka_partition UInt32 COMMENT 'Kafka partition number for replay/debug lineage',
    kafka_offset UInt64 COMMENT 'Kafka offset for replay/debug lineage',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions or django',
    host LowCardinality(String) COMMENT 'Producer host or GitHub runner hostname; LowCardinality for grouping',
    uuid_user Nullable(UUID) COMMENT 'Nullable UUID v7 user identifier; Nullable is not used in ORDER BY',
    ip IPv6 COMMENT 'Producer/client IP normalized to IPv6; missing values use ::',
    url String COMMENT 'NAVER API request URL, NAVER book URL, or event target URL',
    event_type LowCardinality(String) COMMENT 'Book-domain event type, e.g. book.naver.raw.v1 or book.naver.search_log.v1',
    payload String COMMENT 'Raw JSON payload string from Kafka; OLAP processing source; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Event creation timestamp in Asia/Seoul; ORDER BY leading column',
    ingested_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Log/book_events_local', '{replica}')
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, event_uuid)
SETTINGS index_granularity = 8192
COMMENT 'Book-domain raw Kafka event log local replicated table; OLAP 전용; SSOT 아님; TB-scale time-first ORDER BY';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.book_events
ON CLUSTER statground_cluster
(
    event_uuid UUID COMMENT 'Kafka event UUID v7 generated by producer; ClickHouse UUID type; event/log row identifier',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic name; expected book.events; lineage/debug field',
    kafka_partition UInt32 COMMENT 'Kafka partition number for replay/debug lineage',
    kafka_offset UInt64 COMMENT 'Kafka offset for replay/debug lineage',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions or django',
    host LowCardinality(String) COMMENT 'Producer host or GitHub runner hostname; LowCardinality for grouping',
    uuid_user Nullable(UUID) COMMENT 'Nullable UUID v7 user identifier; Nullable is not used in ORDER BY',
    ip IPv6 COMMENT 'Producer/client IP normalized to IPv6; missing values use ::',
    url String COMMENT 'NAVER API request URL, NAVER book URL, or event target URL',
    event_type LowCardinality(String) COMMENT 'Book-domain event type, e.g. book.naver.raw.v1 or book.naver.search_log.v1',
    payload String COMMENT 'Raw JSON payload string from Kafka; OLAP processing source; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Event creation timestamp in Asia/Seoul; distributed read/write field',
    ingested_at DateTime64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Log', 'book_events_local', cityHash64(toString(event_uuid)))
COMMENT 'Book-domain raw Kafka event distributed table; routes writes to 2 shards and reads across replicas; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.kafka_book_events_queue
ON CLUSTER statground_cluster
(
    event_uuid String COMMENT 'UUID v7 string from Kafka JSON message; converted to UUID in materialized views',
    source String COMMENT 'Producer source string from Kafka JSON message',
    host String COMMENT 'Producer host string from Kafka JSON message',
    uuid_user Nullable(String) COMMENT 'Nullable UUID v7 user string from Kafka JSON message',
    ip String COMMENT 'IP string from Kafka JSON message; normalized to IPv6 in materialized views',
    url String COMMENT 'URL string from Kafka JSON message',
    event_type String COMMENT 'Event type string from Kafka JSON message',
    payload String COMMENT 'Raw payload JSON string from Kafka JSON message',
    created_at String COMMENT 'Producer event creation timestamp string from Kafka JSON message; parsed to DateTime64(3, Asia/Seoul) in materialized views'
)
ENGINE = Kafka
SETTINGS
    kafka_broker_list = 'kafka-platform:19092',
    kafka_topic_list = 'book.events',
    kafka_group_name = 'clickhouse_data_book_naver_events_v1',
    kafka_format = 'JSONEachRow',
    kafka_num_consumers = 2,
    kafka_thread_per_consumer = 1,
    kafka_handle_error_mode = 'stream'
COMMENT 'NAVER book Kafka Engine stream table; consumes book.events and filters NAVER/support event types through Materialized Views; OLAP ingestion buffer only; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.book_kafka_parse_error_local
ON CLUSTER statground_cluster
(
    event_uuid UUID COMMENT 'Parsed Kafka event UUID v7 when available; zero UUID when malformed JSON prevents extraction; OLAP parse-error identifier',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic name from _topic virtual column; expected book.events',
    kafka_partition UInt32 COMMENT 'Kafka partition number from _partition virtual column; lineage/debug field',
    kafka_offset UInt64 COMMENT 'Kafka offset from _offset virtual column; lineage/replay/debug field',
    error String COMMENT 'ClickHouse Kafka Engine parse error text from _error; OLAP monitoring only; SSOT 아님',
    raw_message String COMMENT 'Original malformed Kafka message from _raw_message; OLAP debugging only; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Parse-error row creation timestamp in Asia/Seoul; ORDER BY leading column',
    ingested_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'ClickHouse parse-error ingestion timestamp in Asia/Seoul'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Log/book_kafka_parse_error_local', '{replica}')
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, event_uuid)
SETTINGS index_granularity = 8192
COMMENT 'Book-domain Kafka parse error local replicated table; captures malformed book.events rows; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.book_kafka_parse_error
ON CLUSTER statground_cluster
(
    event_uuid UUID COMMENT 'Parsed Kafka event UUID v7 when available; zero UUID when malformed JSON prevents extraction; OLAP parse-error identifier',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic name from _topic virtual column; expected book.events',
    kafka_partition UInt32 COMMENT 'Kafka partition number from _partition virtual column; lineage/debug field',
    kafka_offset UInt64 COMMENT 'Kafka offset from _offset virtual column; lineage/replay/debug field',
    error String COMMENT 'ClickHouse Kafka Engine parse error text from _error; OLAP monitoring only; SSOT 아님',
    raw_message String COMMENT 'Original malformed Kafka message from _raw_message; OLAP debugging only; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Parse-error row creation timestamp in Asia/Seoul; distributed read/write field',
    ingested_at DateTime64(3, 'Asia/Seoul') COMMENT 'ClickHouse parse-error ingestion timestamp in Asia/Seoul'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Log', 'book_kafka_parse_error_local', cityHash64(toString(event_uuid), kafka_partition, kafka_offset))
COMMENT 'Book-domain Kafka parse error distributed table; captures malformed book.events rows; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.naver_book_raw_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'NAVER book row UUID v7 generated by producer; previous UUID preserved when producer can read existing rows',
    provider LowCardinality(String) DEFAULT 'naver' COMMENT 'Book data provider; fixed naver for this table; future providers use separate provider-specific tables',
    version UInt64 COMMENT 'ReplacingMergeTree version; producer uses updated_at Unix milliseconds',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'First-seen row timestamp in Asia/Seoul; preserved for known ISBN when possible; ORDER BY leading column',
    created_log String COMMENT 'First creation log/source string, e.g. github_actions_auto or migration_old_raw_naver',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last producer update timestamp in Asia/Seoul',
    updated_log String COMMENT 'Last update log/source string with search mode/query/sort details',
    collected_at DateTime64(3, 'Asia/Seoul') COMMENT 'Actual NAVER API collection timestamp in Asia/Seoul',
    title String COMMENT 'NAVER Book title text; HTML may be present in upstream response',
    link String COMMENT 'NAVER Book detail URL from NAVER API',
    image String COMMENT 'NAVER Book thumbnail image URL from NAVER API',
    author String COMMENT 'NAVER Book author field; upstream delimiter is preserved',
    discount Nullable(UInt32) COMMENT 'NAVER Book discount price in KRW when provided; NULL means missing or unparsable',
    publisher String COMMENT 'NAVER Book publisher text',
    isbn String COMMENT 'NAVER Book ISBN field as returned by API; may contain ISBN10 and ISBN13 text',
    description String COMMENT 'NAVER Book description text; HTML may be present in upstream response',
    pubdate String COMMENT 'NAVER Book publication date string from API, usually YYYYMMDD',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode such as keyword, author, publisher, mixed, manual, unicode_random_char, aladin_publisher_seed, or migration_old_raw_naver',
    search_query String COMMENT 'Search query submitted to NAVER API',
    search_sort LowCardinality(String) COMMENT 'NAVER API sort parameter such as sim or date',
    search_start UInt16 COMMENT 'NAVER API start parameter; 0 means migration/unknown',
    search_display UInt16 COMMENT 'NAVER API display parameter; 0 means migration/unknown',
    api_total UInt32 COMMENT 'NAVER API total result count observed for this request; 0 means migration/unknown',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions or clickhouse_migration',
    event_uuid UUID COMMENT 'Kafka event UUID v7 that produced this row; migration may reuse source uuid',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic lineage; migration uses migration.statground_book.raw_naver',
    kafka_partition UInt32 COMMENT 'Kafka partition lineage; migration uses 0',
    kafka_offset UInt64 COMMENT 'Kafka offset lineage; migration uses 0',
    payload String COMMENT 'Original producer payload JSON for this row; OLAP raw audit field; SSOT 아님',
    ingested_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Raw/naver_book_raw_local', '{replica}', version)
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, provider, isbn)
SETTINGS index_granularity = 8192
COMMENT 'NAVER Book raw/latest row local replicated table; Kafka-fed OLAP table; SSOT 아님; time-first ORDER BY for TB-scale scans';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.naver_book_raw
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'NAVER book row UUID v7 generated by producer; previous UUID preserved when producer can read existing rows',
    provider LowCardinality(String) COMMENT 'Book data provider; fixed naver for this table',
    version UInt64 COMMENT 'ReplacingMergeTree version; producer uses updated_at Unix milliseconds',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'First-seen row timestamp in Asia/Seoul; distributed read/write field',
    created_log String COMMENT 'First creation log/source string',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last producer update timestamp in Asia/Seoul',
    updated_log String COMMENT 'Last update log/source string with search mode/query/sort details',
    collected_at DateTime64(3, 'Asia/Seoul') COMMENT 'Actual NAVER API collection timestamp in Asia/Seoul',
    title String COMMENT 'NAVER Book title text; HTML may be present in upstream response',
    link String COMMENT 'NAVER Book detail URL from NAVER API',
    image String COMMENT 'NAVER Book thumbnail image URL from NAVER API',
    author String COMMENT 'NAVER Book author field; upstream delimiter is preserved',
    discount Nullable(UInt32) COMMENT 'NAVER Book discount price in KRW when provided; NULL means missing or unparsable',
    publisher String COMMENT 'NAVER Book publisher text',
    isbn String COMMENT 'NAVER Book ISBN field as returned by API; may contain ISBN10 and ISBN13 text',
    description String COMMENT 'NAVER Book description text; HTML may be present in upstream response',
    pubdate String COMMENT 'NAVER Book publication date string from API, usually YYYYMMDD',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode such as keyword, author, publisher, mixed, manual, unicode_random_char, aladin_publisher_seed, or migration_old_raw_naver',
    search_query String COMMENT 'Search query submitted to NAVER API',
    search_sort LowCardinality(String) COMMENT 'NAVER API sort parameter such as sim or date',
    search_start UInt16 COMMENT 'NAVER API start parameter; 0 means migration/unknown',
    search_display UInt16 COMMENT 'NAVER API display parameter; 0 means migration/unknown',
    api_total UInt32 COMMENT 'NAVER API total result count observed for this request; 0 means migration/unknown',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions or clickhouse_migration',
    event_uuid UUID COMMENT 'Kafka event UUID v7 that produced this row; migration may reuse source uuid',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic lineage; migration uses migration.statground_book.raw_naver',
    kafka_partition UInt32 COMMENT 'Kafka partition lineage; migration uses 0',
    kafka_offset UInt64 COMMENT 'Kafka offset lineage; migration uses 0',
    payload String COMMENT 'Original producer payload JSON for this row; OLAP raw audit field; SSOT 아님',
    ingested_at DateTime64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Raw', 'naver_book_raw_local', cityHash64(isbn))
COMMENT 'NAVER Book raw distributed table; sharded by ISBN so repeated ISBN rows route to same shard; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.naver_collect_log_local
ON CLUSTER statground_cluster
(
    log_uuid UUID COMMENT 'Collector log UUID v7 generated by producer payload',
    event_uuid UUID COMMENT 'Kafka event UUID v7 for this log message',
    provider LowCardinality(String) DEFAULT 'naver' COMMENT 'Book provider for this log row; fixed naver',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions',
    host LowCardinality(String) COMMENT 'Producer host or GitHub runner hostname',
    ip IPv6 COMMENT 'Producer/client IP normalized to IPv6; missing values use ::',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode such as keyword, author, publisher, mixed, manual, unicode_random_char, or aladin_publisher_seed',
    search_query String COMMENT 'Search query submitted to NAVER API',
    search_sort LowCardinality(String) COMMENT 'NAVER API sort parameter such as sim or date',
    search_start UInt16 COMMENT 'NAVER API start parameter',
    search_display UInt16 COMMENT 'NAVER API display parameter',
    api_total UInt32 COMMENT 'NAVER API total result count observed for this request',
    fetched_count UInt16 COMMENT 'Number of book items fetched in this API response',
    status LowCardinality(String) COMMENT 'Collection status, e.g. OK or ERROR',
    error String COMMENT 'Error text when status is ERROR; empty when status is OK',
    collect_log String COMMENT 'Producer-side log string with mode/query/sort/start details',
    url String COMMENT 'NAVER API request URL used by the collector',
    payload String COMMENT 'Original collector log payload JSON; OLAP raw audit field; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Collector log timestamp in Asia/Seoul; ORDER BY leading column',
    ingested_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Log/naver_collect_log_local', '{replica}')
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, event_uuid)
SETTINGS index_granularity = 8192
COMMENT 'NAVER Book collector API request log local replicated table; OLAP 전용; SSOT 아님; TB-scale time-first ORDER BY';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.naver_collect_log
ON CLUSTER statground_cluster
(
    log_uuid UUID COMMENT 'Collector log UUID v7 generated by producer payload',
    event_uuid UUID COMMENT 'Kafka event UUID v7 for this log message',
    provider LowCardinality(String) COMMENT 'Book provider for this log row; fixed naver',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions',
    host LowCardinality(String) COMMENT 'Producer host or GitHub runner hostname',
    ip IPv6 COMMENT 'Producer/client IP normalized to IPv6; missing values use ::',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode such as keyword, author, publisher, mixed, manual, unicode_random_char, or aladin_publisher_seed',
    search_query String COMMENT 'Search query submitted to NAVER API',
    search_sort LowCardinality(String) COMMENT 'NAVER API sort parameter such as sim or date',
    search_start UInt16 COMMENT 'NAVER API start parameter',
    search_display UInt16 COMMENT 'NAVER API display parameter',
    api_total UInt32 COMMENT 'NAVER API total result count observed for this request',
    fetched_count UInt16 COMMENT 'Number of book items fetched in this API response',
    status LowCardinality(String) COMMENT 'Collection status, e.g. OK or ERROR',
    error String COMMENT 'Error text when status is ERROR; empty when status is OK',
    collect_log String COMMENT 'Producer-side log string with mode/query/sort/start details',
    url String COMMENT 'NAVER API request URL used by the collector',
    payload String COMMENT 'Original collector log payload JSON; OLAP raw audit field; SSOT 아님',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Collector log timestamp in Asia/Seoul; distributed read/write field',
    ingested_at DateTime64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Log', 'naver_collect_log_local', cityHash64(toString(event_uuid)))
COMMENT 'NAVER Book collector log distributed table; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.naver_commission_link_shotalk_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'UUID v7; Shotalk commission-link response row identifier',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Record first creation timestamp in Asia/Seoul; ORDER BY leading column',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Record update timestamp in Asia/Seoul; ReplacingMergeTree version column',
    isbn String COMMENT 'Related book ISBN string; source value preserved',
    marketplace_name LowCardinality(String) COMMENT 'Requested marketplace name, e.g. Kyobo or YES24',
    marketplace_url String COMMENT 'Original marketplace product URL sent to Shotalk API',
    url_sha256 FixedString(64) COMMENT 'SHA-256 hex digest of marketplace_url; cache/deduplication key',
    api_success UInt8 COMMENT 'Shotalk top-level success flag; 0=false, 1=true',
    api_message String COMMENT 'Shotalk top-level message text',
    data_status LowCardinality(String) COMMENT 'Shotalk data.status value, e.g. success',
    cp_code LowCardinality(String) COMMENT 'Affiliate mall code from Shotalk data.cp_code',
    cp_name LowCardinality(String) COMMENT 'Affiliate mall name from Shotalk data.cp_name',
    cp_icon String COMMENT 'Affiliate mall icon URL from Shotalk data.cp_icon',
    commission_per Decimal(9, 3) COMMENT 'Commission percentage value from Shotalk response',
    product_name String COMMENT 'Product name from Shotalk response',
    product_price_raw String COMMENT 'Raw product price text from Shotalk response',
    product_price_int UInt64 COMMENT 'Parsed product price in KRW; 0 when missing or unparsable',
    product_img String COMMENT 'Product image URL from Shotalk response',
    commission_link String COMMENT 'Generated commission link from Shotalk data.commissionlink',
    error String COMMENT 'HTTP/parsing/business error message when present'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Raw/naver_commission_link_shotalk_local', '{replica}', updated_at)
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, url_sha256, cp_code, uuid)
SETTINGS index_granularity = 8192
COMMENT 'Shotalk API based NAVER/marketplace commission-link result local replicated table; OLAP 전용; SSOT 아님; old table name naver_commision_link_shotalk migrated here';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.naver_commission_link_shotalk
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'UUID v7; Shotalk commission-link response row identifier',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Record first creation timestamp in Asia/Seoul; distributed read/write field',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Record update timestamp in Asia/Seoul; ReplacingMergeTree version column',
    isbn String COMMENT 'Related book ISBN string; source value preserved',
    marketplace_name LowCardinality(String) COMMENT 'Requested marketplace name, e.g. Kyobo or YES24',
    marketplace_url String COMMENT 'Original marketplace product URL sent to Shotalk API',
    url_sha256 FixedString(64) COMMENT 'SHA-256 hex digest of marketplace_url; cache/deduplication key',
    api_success UInt8 COMMENT 'Shotalk top-level success flag; 0=false, 1=true',
    api_message String COMMENT 'Shotalk top-level message text',
    data_status LowCardinality(String) COMMENT 'Shotalk data.status value, e.g. success',
    cp_code LowCardinality(String) COMMENT 'Affiliate mall code from Shotalk data.cp_code',
    cp_name LowCardinality(String) COMMENT 'Affiliate mall name from Shotalk data.cp_name',
    cp_icon String COMMENT 'Affiliate mall icon URL from Shotalk data.cp_icon',
    commission_per Decimal(9, 3) COMMENT 'Commission percentage value from Shotalk response',
    product_name String COMMENT 'Product name from Shotalk response',
    product_price_raw String COMMENT 'Raw product price text from Shotalk response',
    product_price_int UInt64 COMMENT 'Parsed product price in KRW; 0 when missing or unparsable',
    product_img String COMMENT 'Product image URL from Shotalk response',
    commission_link String COMMENT 'Generated commission link from Shotalk data.commissionlink',
    error String COMMENT 'HTTP/parsing/business error message when present'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Raw', 'naver_commission_link_shotalk_local', cityHash64(url_sha256))
COMMENT 'Shotalk API based NAVER/marketplace commission-link result distributed table; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Mart`.naver_book_stats_hourly_local
ON CLUSTER statground_cluster
(
    period_start DateTime64(3, 'Asia/Seoul') COMMENT 'Hourly bucket start timestamp in Asia/Seoul; ORDER BY leading column',
    provider LowCardinality(String) COMMENT 'Book provider; fixed naver for this mart table',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode dimension',
    rows_state AggregateFunction(count) COMMENT 'Aggregate state for number of NAVER raw rows inserted into ClickHouse',
    isbn_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique ISBN count',
    author_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique author field count',
    publisher_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique publisher count',
    min_collected_at_state AggregateFunction(min, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for earliest collected_at timestamp in bucket',
    max_collected_at_state AggregateFunction(max, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for latest collected_at timestamp in bucket'
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Mart/naver_book_stats_hourly_local', '{replica}')
PARTITION BY toYYYYMM(period_start)
ORDER BY (period_start, provider, search_mode)
SETTINGS index_granularity = 8192
COMMENT 'NAVER Book hourly statistics local aggregate table; generated inside ClickHouse; GitHub repo does not generate stats; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Mart`.naver_book_stats_hourly
ON CLUSTER statground_cluster
(
    period_start DateTime64(3, 'Asia/Seoul') COMMENT 'Hourly bucket start timestamp in Asia/Seoul; distributed read field',
    provider LowCardinality(String) COMMENT 'Book provider; fixed naver for this mart table',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode dimension',
    rows_state AggregateFunction(count) COMMENT 'Aggregate state for number of NAVER raw rows inserted into ClickHouse',
    isbn_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique ISBN count',
    author_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique author field count',
    publisher_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique publisher count',
    min_collected_at_state AggregateFunction(min, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for earliest collected_at timestamp in bucket',
    max_collected_at_state AggregateFunction(max, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for latest collected_at timestamp in bucket'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Mart', 'naver_book_stats_hourly_local', cityHash64(provider, search_mode))
COMMENT 'NAVER Book hourly statistics distributed aggregate table; query with countMerge/uniqCombined64Merge; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Mart`.naver_book_stats_daily_local
ON CLUSTER statground_cluster
(
    period_start DateTime64(3, 'Asia/Seoul') COMMENT 'Daily bucket start timestamp in Asia/Seoul; ORDER BY leading column',
    provider LowCardinality(String) COMMENT 'Book provider; fixed naver for this mart table',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode dimension',
    rows_state AggregateFunction(count) COMMENT 'Aggregate state for number of NAVER raw rows inserted into ClickHouse',
    isbn_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique ISBN count',
    author_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique author field count',
    publisher_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique publisher count',
    min_collected_at_state AggregateFunction(min, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for earliest collected_at timestamp in bucket',
    max_collected_at_state AggregateFunction(max, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for latest collected_at timestamp in bucket'
)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Mart/naver_book_stats_daily_local', '{replica}')
PARTITION BY toYYYYMM(period_start)
ORDER BY (period_start, provider, search_mode)
SETTINGS index_granularity = 8192
COMMENT 'NAVER Book daily statistics local aggregate table; generated inside ClickHouse; GitHub repo does not generate stats; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Mart`.naver_book_stats_daily
ON CLUSTER statground_cluster
(
    period_start DateTime64(3, 'Asia/Seoul') COMMENT 'Daily bucket start timestamp in Asia/Seoul; distributed read field',
    provider LowCardinality(String) COMMENT 'Book provider; fixed naver for this mart table',
    search_mode LowCardinality(String) COMMENT 'Crawler search mode dimension',
    rows_state AggregateFunction(count) COMMENT 'Aggregate state for number of NAVER raw rows inserted into ClickHouse',
    isbn_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique ISBN count',
    author_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique author field count',
    publisher_uniq_state AggregateFunction(uniqCombined64, String) COMMENT 'Aggregate state for approximate unique publisher count',
    min_collected_at_state AggregateFunction(min, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for earliest collected_at timestamp in bucket',
    max_collected_at_state AggregateFunction(max, DateTime64(3, 'Asia/Seoul')) COMMENT 'Aggregate state for latest collected_at timestamp in bucket'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Mart', 'naver_book_stats_daily_local', cityHash64(provider, search_mode))
COMMENT 'NAVER Book daily statistics distributed aggregate table; query with countMerge/uniqCombined64Merge; OLAP 전용; SSOT 아님';

/* -------------------------------------------------------------------------
   Additional source-agnostic / non-NAVER-only book tables.
   These tables were added after reviewing older backup and Shotalk objects:
   - statground_book.backup_v_book_list_all
   - statground_book.backup_marketplace_url
   - statground_book.raw_aladin_publisher_cache
   - log.log_shotalk_search
--------------------------------------------------------------------------- */

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.legacy_book_catalog_local
ON CLUSTER statground_cluster
(
    rnum UInt64 COMMENT 'Legacy row number from statground_book.backup_v_book_list_all; preserved for audit only',
    uuid UUID COMMENT 'Book UUID from legacy multi-source catalog; UUID v7 policy preferred, source value preserved; OLAP 전용 식별자',
    dedupe_key String COMMENT 'Legacy deduplication key used by earlier multi-source book catalog pipeline',
    isbn13 String COMMENT 'ISBN-13 string when available; source value preserved',
    isbn10 String COMMENT 'ISBN-10 string when available; source value preserved',
    oclc String COMMENT 'OCLC identifier string from legacy source when available',
    lccn String COMMENT 'Library of Congress Control Number string from legacy source when available',
    olid String COMMENT 'Open Library identifier string from legacy source when available',
    google_id String COMMENT 'Google Books identifier string from legacy source when available',
    naver_id String COMMENT 'NAVER identifier string from legacy source when available; not limited to current NAVER API raw table',
    title String COMMENT 'Book title from legacy multi-source catalog',
    subtitle String COMMENT 'Book subtitle from legacy multi-source catalog',
    authors String COMMENT 'Author list text from legacy multi-source catalog; delimiter/source format preserved',
    publisher LowCardinality(String) COMMENT 'Publisher text from legacy multi-source catalog; LowCardinality for grouping',
    published_date String COMMENT 'Publication date string from legacy source; source format preserved',
    publish_year UInt16 COMMENT 'Publication year parsed by legacy pipeline; 0 means missing or unknown',
    language LowCardinality(String) COMMENT 'Book language code/text from legacy source; LowCardinality for grouping',
    description String COMMENT 'Book description text from legacy multi-source catalog',
    subjects String COMMENT 'Subjects text from legacy source; serialized list/text format preserved',
    categories String COMMENT 'Categories text from legacy source; serialized list/text format preserved',
    page_count UInt16 COMMENT 'Page count parsed by legacy pipeline; 0 means missing or unknown',
    cover_url String COMMENT 'Book cover image URL from legacy source',
    info_url String COMMENT 'Book information URL from legacy source',
    source_primary LowCardinality(String) COMMENT 'Primary data source selected by legacy pipeline, e.g. google, openlibrary, naver',
    source_list String COMMENT 'Serialized list of sources that contributed to this legacy row',
    raw_json String COMMENT 'Original book raw payload serialized as JSON text; OLAP raw audit field; SSOT 아님',
    raw_json_hash String COMMENT 'Hash of raw_json generated by legacy pipeline; source value preserved',
    last_query String COMMENT 'Last query text used by the legacy pipeline for this book row',
    last_query_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last query timestamp from legacy pipeline in Asia/Seoul',
    active UInt8 COMMENT 'Legacy active flag; 0=inactive, 1=active',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Legacy row creation timestamp in Asia/Seoul; ORDER BY leading column',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Legacy row update timestamp in Asia/Seoul; ReplacingMergeTree version column',
    last_seen_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last-seen timestamp from legacy multi-source pipeline in Asia/Seoul',
    created_log String COMMENT 'Creation metadata serialized as JSON text; OLAP log field; SSOT 아님',
    updated_log String COMMENT 'Update metadata serialized as JSON text; OLAP log field; SSOT 아님',
    table_of_contents String COMMENT 'Table of contents text from legacy source when available',
    price String COMMENT 'Price text from legacy source; source format preserved',
    migrated_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'Migration ingestion timestamp in Asia/Seoul; OLAP lineage only',
    source_table LowCardinality(String) DEFAULT 'statground_book.backup_v_book_list_all' COMMENT 'Original source table name for migration lineage; OLAP 전용'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Raw/legacy_book_catalog_local', '{replica}', updated_at)
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, source_primary, uuid)
SETTINGS index_granularity = 8192
COMMENT 'Legacy multi-source book catalog local replicated table migrated from backup_v_book_list_all; not NAVER-only; OLAP 전용; SSOT 아님; time-first ORDER BY for TB-scale historical scans';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.legacy_book_catalog
ON CLUSTER statground_cluster
(
    rnum UInt64 COMMENT 'Legacy row number from statground_book.backup_v_book_list_all; preserved for audit only',
    uuid UUID COMMENT 'Book UUID from legacy multi-source catalog; UUID v7 policy preferred, source value preserved; OLAP 전용 식별자',
    dedupe_key String COMMENT 'Legacy deduplication key used by earlier multi-source book catalog pipeline',
    isbn13 String COMMENT 'ISBN-13 string when available; source value preserved',
    isbn10 String COMMENT 'ISBN-10 string when available; source value preserved',
    oclc String COMMENT 'OCLC identifier string from legacy source when available',
    lccn String COMMENT 'Library of Congress Control Number string from legacy source when available',
    olid String COMMENT 'Open Library identifier string from legacy source when available',
    google_id String COMMENT 'Google Books identifier string from legacy source when available',
    naver_id String COMMENT 'NAVER identifier string from legacy source when available; not limited to current NAVER API raw table',
    title String COMMENT 'Book title from legacy multi-source catalog',
    subtitle String COMMENT 'Book subtitle from legacy multi-source catalog',
    authors String COMMENT 'Author list text from legacy multi-source catalog; delimiter/source format preserved',
    publisher LowCardinality(String) COMMENT 'Publisher text from legacy multi-source catalog; LowCardinality for grouping',
    published_date String COMMENT 'Publication date string from legacy source; source format preserved',
    publish_year UInt16 COMMENT 'Publication year parsed by legacy pipeline; 0 means missing or unknown',
    language LowCardinality(String) COMMENT 'Book language code/text from legacy source; LowCardinality for grouping',
    description String COMMENT 'Book description text from legacy multi-source catalog',
    subjects String COMMENT 'Subjects text from legacy source; serialized list/text format preserved',
    categories String COMMENT 'Categories text from legacy source; serialized list/text format preserved',
    page_count UInt16 COMMENT 'Page count parsed by legacy pipeline; 0 means missing or unknown',
    cover_url String COMMENT 'Book cover image URL from legacy source',
    info_url String COMMENT 'Book information URL from legacy source',
    source_primary LowCardinality(String) COMMENT 'Primary data source selected by legacy pipeline, e.g. google, openlibrary, naver',
    source_list String COMMENT 'Serialized list of sources that contributed to this legacy row',
    raw_json String COMMENT 'Original book raw payload serialized as JSON text; OLAP raw audit field; SSOT 아님',
    raw_json_hash String COMMENT 'Hash of raw_json generated by legacy pipeline; source value preserved',
    last_query String COMMENT 'Last query text used by the legacy pipeline for this book row',
    last_query_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last query timestamp from legacy pipeline in Asia/Seoul',
    active UInt8 COMMENT 'Legacy active flag; 0=inactive, 1=active',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Legacy row creation timestamp in Asia/Seoul; distributed read/write field',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Legacy row update timestamp in Asia/Seoul',
    last_seen_at DateTime64(3, 'Asia/Seoul') COMMENT 'Last-seen timestamp from legacy multi-source pipeline in Asia/Seoul',
    created_log String COMMENT 'Creation metadata serialized as JSON text; OLAP log field; SSOT 아님',
    updated_log String COMMENT 'Update metadata serialized as JSON text; OLAP log field; SSOT 아님',
    table_of_contents String COMMENT 'Table of contents text from legacy source when available',
    price String COMMENT 'Price text from legacy source; source format preserved',
    migrated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Migration ingestion timestamp in Asia/Seoul; OLAP lineage only',
    source_table LowCardinality(String) COMMENT 'Original source table name for migration lineage; OLAP 전용'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Raw', 'legacy_book_catalog_local', cityHash64(toString(uuid)))
COMMENT 'Legacy multi-source book catalog distributed table migrated from backup_v_book_list_all; not NAVER-only; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.book_marketplace_url_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'Marketplace URL row UUID from legacy table; UUID v7 policy preferred, source value preserved; OLAP 전용 식별자',
    uuid_book UUID COMMENT 'Book UUID v7 referenced by this marketplace URL; source value preserved; Nullable not used in ORDER BY',
    uuid_marketplace UUID COMMENT 'Marketplace UUID v7 referenced by this URL; source value preserved',
    url String COMMENT 'Marketplace product URL string; source value preserved',
    active UInt8 COMMENT 'Active flag from legacy table; 0=inactive, 1=active',
    uuid_affiliate Nullable(UUID) COMMENT 'Nullable affiliate UUID v7 when available; Nullable column is not part of ORDER BY',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Row creation timestamp in Asia/Seoul; ORDER BY leading column',
    created_log String COMMENT 'Creation log metadata serialized as JSON text; OLAP only; SSOT 아님',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Row update timestamp in Asia/Seoul; ReplacingMergeTree version column',
    updated_log String COMMENT 'Update log metadata serialized as JSON text; OLAP only; SSOT 아님',
    type LowCardinality(String) COMMENT 'Marketplace URL type/category from legacy table; LowCardinality for grouping',
    migrated_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'Migration/Kafka ingestion timestamp in Asia/Seoul; OLAP lineage only',
    source_table LowCardinality(String) DEFAULT 'statground_book.backup_marketplace_url' COMMENT 'Original source table or producer source for lineage; OLAP 전용'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Raw/book_marketplace_url_local', '{replica}', updated_at)
PARTITION BY toYYYYMM(created_at)
ORDER BY (created_at, uuid_book, type, uuid)
SETTINGS index_granularity = 8192
COMMENT 'Book marketplace URL relation local replicated table migrated from backup_marketplace_url; provider-agnostic; OLAP 전용; SSOT 아님; time-first ORDER BY for TB-scale scans';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.book_marketplace_url
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'Marketplace URL row UUID from legacy table; UUID v7 policy preferred, source value preserved; OLAP 전용 식별자',
    uuid_book UUID COMMENT 'Book UUID v7 referenced by this marketplace URL; source value preserved; Nullable not used in ORDER BY',
    uuid_marketplace UUID COMMENT 'Marketplace UUID v7 referenced by this URL; source value preserved',
    url String COMMENT 'Marketplace product URL string; source value preserved',
    active UInt8 COMMENT 'Active flag from legacy table; 0=inactive, 1=active',
    uuid_affiliate Nullable(UUID) COMMENT 'Nullable affiliate UUID v7 when available; Nullable column is not part of ORDER BY',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Row creation timestamp in Asia/Seoul; distributed read/write field',
    created_log String COMMENT 'Creation log metadata serialized as JSON text; OLAP only; SSOT 아님',
    updated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Row update timestamp in Asia/Seoul',
    updated_log String COMMENT 'Update log metadata serialized as JSON text; OLAP only; SSOT 아님',
    type LowCardinality(String) COMMENT 'Marketplace URL type/category from legacy table; LowCardinality for grouping',
    migrated_at DateTime64(3, 'Asia/Seoul') COMMENT 'Migration/Kafka ingestion timestamp in Asia/Seoul; OLAP lineage only',
    source_table LowCardinality(String) COMMENT 'Original source table or producer source for lineage; OLAP 전용'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Raw', 'book_marketplace_url_local', cityHash64(toString(uuid_book)))
COMMENT 'Book marketplace URL relation distributed table migrated from backup_marketplace_url; provider-agnostic; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.aladin_publisher_cache_local
ON CLUSTER statground_cluster
(
    publisher String COMMENT 'Aladin publisher name raw text collected from publisher list page',
    collected_at DateTime64(3, 'Asia/Seoul') COMMENT 'Collection timestamp in Asia/Seoul; ORDER BY leading column',
    detected_last_page UInt32 COMMENT 'Detected maximum Aladin publisher-list page at collection time',
    run_uuid UUID COMMENT 'Batch run UUID v7 generated by producer; OLAP 전용; SSOT 아님',
    source LowCardinality(String) COMMENT 'Collection source; expected aladin or github_actions_aladin'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Log/aladin_publisher_cache_local', '{replica}')
PARTITION BY toYYYYMM(collected_at)
ORDER BY (collected_at, detected_last_page, publisher)
SETTINGS index_granularity = 8192
COMMENT 'Aladin publisher-list cache/log local replicated table; used by GitHub Actions as read-through cache; OLAP 전용; SSOT 아님; time-first ORDER BY';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Log`.aladin_publisher_cache
ON CLUSTER statground_cluster
(
    publisher String COMMENT 'Aladin publisher name raw text collected from publisher list page',
    collected_at DateTime64(3, 'Asia/Seoul') COMMENT 'Collection timestamp in Asia/Seoul; distributed read/write field',
    detected_last_page UInt32 COMMENT 'Detected maximum Aladin publisher-list page at collection time',
    run_uuid UUID COMMENT 'Batch run UUID v7 generated by producer; OLAP 전용; SSOT 아님',
    source LowCardinality(String) COMMENT 'Collection source; expected aladin or github_actions_aladin'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Log', 'aladin_publisher_cache_local', cityHash64(publisher, toString(run_uuid)))
COMMENT 'Aladin publisher-list cache/log distributed table; used by GitHub Actions as read-through cache; OLAP 전용; SSOT 아님';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.shotalk_search_result_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'UUID v7 row identifier from Shotalk search result; source value preserved on migration',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Search result creation timestamp in Asia/Seoul',
    q String COMMENT 'Search query text submitted to Shotalk',
    req_limit UInt16 COMMENT 'Requested limit value',
    req_page UInt32 COMMENT 'Requested page number',
    item_rank UInt16 COMMENT 'Item rank within search result page',
    title String COMMENT 'Product title returned by Shotalk search',
    price UInt32 COMMENT 'Product price in KRW numeric value; 0 means missing or unparsable',
    photo_url String COMMENT 'Product image URL returned by Shotalk search',
    cp_code LowCardinality(String) COMMENT 'Shopping mall code returned by Shotalk',
    cp_name LowCardinality(String) COMMENT 'Shopping mall name returned by Shotalk',
    cp_icon_url String COMMENT 'Shopping mall icon URL returned by Shotalk',
    commission_link String COMMENT 'Shotalk commission link; logical uniqueness key for this latest-result table',
    version UInt64 COMMENT 'ReplacingMergeTree version; old table uses created_at-derived version; larger value wins'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/Data_Book_NAVER_Raw/shotalk_search_result_local', '{replica}', version)
PARTITION BY toYYYYMM(created_at)
ORDER BY commission_link
SETTINGS index_granularity = 8192
COMMENT 'Shotalk product search result latest table migrated from log.log_shotalk_search; OLAP 전용; SSOT 아님; ORDER BY commission_link is deliberate to preserve logical unique/replacing semantics';

CREATE TABLE IF NOT EXISTS `Data_Book_NAVER_Raw`.shotalk_search_result
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'UUID v7 row identifier from Shotalk search result; source value preserved on migration',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Search result creation timestamp in Asia/Seoul; distributed read/write field',
    q String COMMENT 'Search query text submitted to Shotalk',
    req_limit UInt16 COMMENT 'Requested limit value',
    req_page UInt32 COMMENT 'Requested page number',
    item_rank UInt16 COMMENT 'Item rank within search result page',
    title String COMMENT 'Product title returned by Shotalk search',
    price UInt32 COMMENT 'Product price in KRW numeric value; 0 means missing or unparsable',
    photo_url String COMMENT 'Product image URL returned by Shotalk search',
    cp_code LowCardinality(String) COMMENT 'Shopping mall code returned by Shotalk',
    cp_name LowCardinality(String) COMMENT 'Shopping mall name returned by Shotalk',
    cp_icon_url String COMMENT 'Shopping mall icon URL returned by Shotalk',
    commission_link String COMMENT 'Shotalk commission link; logical uniqueness key for this latest-result table',
    version UInt64 COMMENT 'ReplacingMergeTree version; old table uses created_at-derived version; larger value wins'
)
ENGINE = Distributed('statground_cluster', 'Data_Book_NAVER_Raw', 'shotalk_search_result_local', cityHash64(commission_link))
COMMENT 'Shotalk product search result latest distributed table migrated from log.log_shotalk_search; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Log`.mv_kafka_book_events_to_book_events
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Log`.book_events
AS
SELECT
    ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000')) AS event_uuid,
    _topic AS kafka_topic,
    toUInt32(_partition) AS kafka_partition,
    toUInt64(_offset) AS kafka_offset,
    k.source AS source,
    k.host AS host,
    toUUIDOrNull(nullIf(k.uuid_user, '')) AS uuid_user,
    toIPv6OrDefault(k.ip) AS ip,
    k.url AS url,
    k.event_type AS event_type,
    k.payload AS payload,
    coalesce(
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS created_at,
    now64(3, 'Asia/Seoul') AS ingested_at
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0;

ALTER TABLE `Data_Book_NAVER_Log`.mv_kafka_book_events_to_book_events
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from valid Kafka Engine book.events rows to Data_Book_NAVER_Log.book_events; malformed rows go to book_kafka_parse_error; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Log`.mv_kafka_book_events_to_parse_error
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Log`.book_kafka_parse_error
AS
SELECT
    ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000')) AS event_uuid,
    _topic AS kafka_topic,
    toUInt32(_partition) AS kafka_partition,
    toUInt64(_offset) AS kafka_offset,
    _error AS error,
    _raw_message AS raw_message,
    now64(3, 'Asia/Seoul') AS created_at,
    now64(3, 'Asia/Seoul') AS ingested_at
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) > 0;

ALTER TABLE `Data_Book_NAVER_Log`.mv_kafka_book_events_to_parse_error
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from malformed Kafka Engine book.events rows to Data_Book_NAVER_Log.book_kafka_parse_error; OLAP monitoring; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_naver_book_raw
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Raw`.naver_book_raw
AS
SELECT
    ifNull(toUUIDOrNull(JSONExtractString(k.payload, 'uuid')), ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000'))) AS uuid,
    'naver' AS provider,
    toUInt64OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'version'), ''), '0')) AS version,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'created_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS created_at,
    JSONExtractString(k.payload, 'created_log') AS created_log,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'updated_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS updated_at,
    JSONExtractString(k.payload, 'updated_log') AS updated_log,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'collected_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS collected_at,
    JSONExtractString(k.payload, 'title') AS title,
    JSONExtractString(k.payload, 'link') AS link,
    JSONExtractString(k.payload, 'image') AS image,
    JSONExtractString(k.payload, 'author') AS author,
    toUInt32OrNull(nullIf(nullIf(JSONExtractRaw(k.payload, 'discount'), ''), 'null')) AS discount,
    JSONExtractString(k.payload, 'publisher') AS publisher,
    JSONExtractString(k.payload, 'isbn') AS isbn,
    JSONExtractString(k.payload, 'description') AS description,
    JSONExtractString(k.payload, 'pubdate') AS pubdate,
    JSONExtractString(k.payload, 'search_mode') AS search_mode,
    JSONExtractString(k.payload, 'search_query') AS search_query,
    JSONExtractString(k.payload, 'search_sort') AS search_sort,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'search_start'), ''), '0')) AS search_start,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'search_display'), ''), '0')) AS search_display,
    toUInt32OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'api_total'), ''), '0')) AS api_total,
    if(notEmpty(JSONExtractString(k.payload, 'source')), JSONExtractString(k.payload, 'source'), k.source) AS source,
    ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000')) AS event_uuid,
    _topic AS kafka_topic,
    toUInt32(_partition) AS kafka_partition,
    toUInt64(_offset) AS kafka_offset,
    k.payload AS payload,
    now64(3, 'Asia/Seoul') AS ingested_at
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0
  AND k.event_type = 'book.naver.raw.v1'
  AND notEmpty(JSONExtractString(k.payload, 'isbn'));

ALTER TABLE `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_naver_book_raw
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from Kafka book.naver.raw.v1 events to Data_Book_NAVER_Raw.naver_book_raw; uses toString(k.created_at) to support String/DateTime64 Kafka schemas; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Log`.mv_kafka_book_events_to_naver_collect_log
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Log`.naver_collect_log
AS
SELECT
    ifNull(toUUIDOrNull(JSONExtractString(k.payload, 'log_uuid')), ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000'))) AS log_uuid,
    ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000')) AS event_uuid,
    'naver' AS provider,
    k.source AS source,
    k.host AS host,
    toIPv6OrDefault(k.ip) AS ip,
    JSONExtractString(k.payload, 'search_mode') AS search_mode,
    JSONExtractString(k.payload, 'search_query') AS search_query,
    JSONExtractString(k.payload, 'search_sort') AS search_sort,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'search_start'), ''), '0')) AS search_start,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'search_display'), ''), '0')) AS search_display,
    toUInt32OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'api_total'), ''), '0')) AS api_total,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'fetched_count'), ''), '0')) AS fetched_count,
    JSONExtractString(k.payload, 'status') AS status,
    JSONExtractString(k.payload, 'error') AS error,
    JSONExtractString(k.payload, 'collect_log') AS collect_log,
    k.url AS url,
    k.payload AS payload,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'created_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS created_at,
    now64(3, 'Asia/Seoul') AS ingested_at
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0
  AND k.event_type = 'book.naver.search_log.v1';

ALTER TABLE `Data_Book_NAVER_Log`.mv_kafka_book_events_to_naver_collect_log
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from Kafka book.naver.search_log.v1 events to Data_Book_NAVER_Log.naver_collect_log; uses toString(k.created_at) to support String/DateTime64 Kafka schemas; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Mart`.mv_naver_book_raw_to_stats_hourly
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Mart`.naver_book_stats_hourly_local
AS
SELECT
    toStartOfHour(collected_at) AS period_start,
    provider AS provider,
    search_mode AS search_mode,
    countState() AS rows_state,
    uniqCombined64State(isbn) AS isbn_uniq_state,
    uniqCombined64State(author) AS author_uniq_state,
    uniqCombined64State(publisher) AS publisher_uniq_state,
    minState(collected_at) AS min_collected_at_state,
    maxState(collected_at) AS max_collected_at_state
FROM `Data_Book_NAVER_Raw`.naver_book_raw_local
GROUP BY
    period_start,
    provider,
    search_mode;

ALTER TABLE `Data_Book_NAVER_Mart`.mv_naver_book_raw_to_stats_hourly
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view that stores NAVER Book hourly statistics inside ClickHouse; GitHub repo does not generate stats; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Mart`.mv_naver_book_raw_to_stats_daily
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Mart`.naver_book_stats_daily_local
AS
SELECT
    toStartOfDay(collected_at) AS period_start,
    provider AS provider,
    search_mode AS search_mode,
    countState() AS rows_state,
    uniqCombined64State(isbn) AS isbn_uniq_state,
    uniqCombined64State(author) AS author_uniq_state,
    uniqCombined64State(publisher) AS publisher_uniq_state,
    minState(collected_at) AS min_collected_at_state,
    maxState(collected_at) AS max_collected_at_state
FROM `Data_Book_NAVER_Raw`.naver_book_raw_local
GROUP BY
    period_start,
    provider,
    search_mode;

ALTER TABLE `Data_Book_NAVER_Mart`.mv_naver_book_raw_to_stats_daily
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view that stores NAVER Book daily statistics inside ClickHouse; GitHub repo does not generate stats; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Log`.mv_kafka_book_events_to_aladin_publisher_cache
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Log`.aladin_publisher_cache
AS
SELECT
    JSONExtractString(k.payload, 'publisher') AS publisher,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'collected_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS collected_at,
    toUInt32OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'detected_last_page'), ''), '0')) AS detected_last_page,
    ifNull(toUUIDOrNull(if(notEmpty(JSONExtractString(k.payload, 'run_uuid')), JSONExtractString(k.payload, 'run_uuid'), k.event_uuid)), toUUID('00000000-0000-0000-0000-000000000000')) AS run_uuid,
    if(notEmpty(JSONExtractString(k.payload, 'source')), JSONExtractString(k.payload, 'source'), 'aladin') AS source
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0
  AND k.event_type = 'book.aladin.publisher_cache.v1'
  AND notEmpty(JSONExtractString(k.payload, 'publisher'));

ALTER TABLE `Data_Book_NAVER_Log`.mv_kafka_book_events_to_aladin_publisher_cache
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from Kafka book.aladin.publisher_cache.v1 events to Data_Book_NAVER_Log.aladin_publisher_cache; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_book_marketplace_url
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Raw`.book_marketplace_url
AS
SELECT
    ifNull(toUUIDOrNull(JSONExtractString(k.payload, 'uuid')), ifNull(toUUIDOrNull(k.event_uuid), toUUID('00000000-0000-0000-0000-000000000000'))) AS uuid,
    ifNull(toUUIDOrNull(JSONExtractString(k.payload, 'uuid_book')), toUUID('00000000-0000-0000-0000-000000000000')) AS uuid_book,
    ifNull(toUUIDOrNull(JSONExtractString(k.payload, 'uuid_marketplace')), toUUID('00000000-0000-0000-0000-000000000000')) AS uuid_marketplace,
    JSONExtractString(k.payload, 'url') AS url,
    toUInt8OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'active'), ''), '0')) AS active,
    toUUIDOrNull(nullIf(JSONExtractString(k.payload, 'uuid_affiliate'), '')) AS uuid_affiliate,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'created_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS created_at,
    JSONExtractString(k.payload, 'created_log') AS created_log,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'updated_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS updated_at,
    JSONExtractString(k.payload, 'updated_log') AS updated_log,
    JSONExtractString(k.payload, 'type') AS type,
    now64(3, 'Asia/Seoul') AS migrated_at,
    if(notEmpty(JSONExtractString(k.payload, 'source_table')), JSONExtractString(k.payload, 'source_table'), k.source) AS source_table
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0
  AND k.event_type = 'book.marketplace.url.v1'
  AND notEmpty(JSONExtractString(k.payload, 'uuid'))
  AND notEmpty(JSONExtractString(k.payload, 'uuid_book'))
  AND notEmpty(JSONExtractString(k.payload, 'uuid_marketplace'));

ALTER TABLE `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_book_marketplace_url
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from Kafka book.marketplace.url.v1 events to Data_Book_NAVER_Raw.book_marketplace_url; provider-agnostic marketplace URL ingestion; OLAP 전용; SSOT 아님';

CREATE MATERIALIZED VIEW IF NOT EXISTS `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_shotalk_search_result
ON CLUSTER statground_cluster
TO `Data_Book_NAVER_Raw`.shotalk_search_result
AS
SELECT
    ifNull(toUUIDOrNull(if(notEmpty(JSONExtractString(k.payload, 'uuid')), JSONExtractString(k.payload, 'uuid'), k.event_uuid)), toUUID('00000000-0000-0000-0000-000000000000')) AS uuid,
    coalesce(
        parseDateTime64BestEffortOrNull(JSONExtractString(k.payload, 'created_at'), 3, 'Asia/Seoul'),
        parseDateTime64BestEffortOrNull(toString(k.created_at), 3, 'Asia/Seoul'),
        now64(3, 'Asia/Seoul')
    ) AS created_at,
    JSONExtractString(k.payload, 'q') AS q,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'req_limit'), ''), '0')) AS req_limit,
    toUInt32OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'req_page'), ''), '0')) AS req_page,
    toUInt16OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'item_rank'), ''), '0')) AS item_rank,
    JSONExtractString(k.payload, 'title') AS title,
    toUInt32OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'price'), ''), '0')) AS price,
    JSONExtractString(k.payload, 'photo_url') AS photo_url,
    JSONExtractString(k.payload, 'cp_code') AS cp_code,
    JSONExtractString(k.payload, 'cp_name') AS cp_name,
    JSONExtractString(k.payload, 'cp_icon_url') AS cp_icon_url,
    JSONExtractString(k.payload, 'commission_link') AS commission_link,
    if(
        toUInt64OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'version'), ''), '0')) = 0,
        toUInt64(toUnixTimestamp64Milli(now64(3, 'Asia/Seoul'))),
        toUInt64OrZero(ifNull(nullIf(JSONExtractRaw(k.payload, 'version'), ''), '0'))
    ) AS version
FROM `Data_Book_NAVER_Log`.kafka_book_events_queue AS k
WHERE length(ifNull(_error, '')) = 0
  AND k.event_type = 'book.shotalk.search_result.v1'
  AND notEmpty(JSONExtractString(k.payload, 'commission_link'));

ALTER TABLE `Data_Book_NAVER_Raw`.mv_kafka_book_events_to_shotalk_search_result
ON CLUSTER statground_cluster
MODIFY COMMENT 'Materialized view from Kafka book.shotalk.search_result.v1 events to Data_Book_NAVER_Raw.shotalk_search_result; OLAP 전용; SSOT 아님';
